### ISSUE TITLE
Why is button/input support left out?

### ISSUE THREAD

**Issue by FossPrime** [jalkoby/phoenix_ujs#1]
https://github.com/jalkoby/phoenix_ujs/blob/master/src/ujs/dom.js#L11

I found that strange, vanilla.ujs does support button elements

**Comment by jalkoby** [comment]
what is the use-case to use buttons? Yes, they part of html, but to proceed the url you need to wrap a button inside a form

**Comment by FossPrime** [comment]
<button type="submit">

**Comment by jalkoby** [comment]
So you can add ujs tag on the form which contains this button and use the library

**Comment by FossPrime** [comment]
As I did. That said, button does work on vanilla.js, if the goal is to have
feature parity... I found it a strange omission and thought there was a
good reason for it. A comment may be helpful "// button and inputs are not
supported. Deal with it B)"

**Comment by jalkoby** [comment]
@rayfoss probably, you have a point. I just used specification from their [wiki](https://github.com/rails/jquery-ujs/wiki/Unobtrusive-scripting-support-for-jQuery)
