### ISSUE TITLE
Form parameters doesnt pass to controller

### ISSUE THREAD

**Issue by dokuzbir** [jalkoby/phoenix_ujs#10]
I get console.log succes but paramaters doesnt pass to controller only empty map %{}

> <div id="search-form">
>     <%= form_for @conn, search_path(@conn, :search), [ method: :get, ujs_remote: "ujs-remote"] , fn f ->%>
>       <div id="search-group"> 
>           <div class="col-xs-8 col-sm-offset-1 col-sm-7" >
>           <%= text_input f, :q, placeholder: "search", required: true, id: "search-input", class: "fontAwesome form-control input-lg", data: [behaviour: "autocomplete"] %>
>           </div>
>           <div class="col-xs-4 col-sm-3">
>   <%= submit "Search", class: "btn btn-bordered btn-green btn-block btn-lg"%>
>     
>           </div>
>       </div>
>     <% end%>    
>   </div>
> 
> <script>
> 
>  document.addEventListener('ajax:success', function(e) {
>   console.log("succes")
> });
> </script>

**Comment by jalkoby** [comment]
thank you for submitting the issue. Please upgrade to 0.4.0 - it will fix the case with "GET" remote forms
