### ISSUE TITLE
case sensitivity of x-requested-with

### ISSUE THREAD

**Issue by markschultz** [jalkoby/phoenix_ujs#11]
it seems that the **value** of the header being case sensitive is undefined by http spec. In this library you use 
`xhr.setRequestHeader('X-Requested-With', 'XmlHttpRequest');`
when the standard I've seen around other libraries is "XMLHttpRequest". Could this be changed? I can submit a pr if yes.

**Comment by jalkoby** [comment]
Probably you’re right. Please do a pr and I’ll merge it

**Comment by jalkoby** [comment]
0.4.1 is released
