### ISSUE TITLE
FormData: Form remote fails in older browers

### ISSUE THREAD

**Issue by udfalkso** [jalkoby/phoenix_ujs#2]
I'm getting lots of forms not working on my site.  They seem to submit without xhr, or are missing form fields.  

The common denominator seems to be older Windows and Android environments.  My hunch is that lack of support for FormData is the culprit.  

I'm trying to alter form.js to handle this case, will submit a PR if I succeed.  It might just be easier for me to add a jquery dependency however (I'm already using it for other reasons).  

Thanks!

**Comment by jalkoby** [comment]
Hi @udfalkso . 

According to https://developer.mozilla.org/en/docs/Web/API/FormData FormData is works fine on Android since 3.0, so the modern browsers should play well with `phoenix_js`(if not - please share your use-cases and details). Adding jQuery as a dependency is not an option, so you can add this polyfill https://www.npmjs.com/package/formdata-polyfill

**Comment by jalkoby** [comment]
or this one https://www.npmjs.com/package/js-polyfills

**Comment by udfalkso** [comment]
Yes it works fine in modern browsers.  It's the non-modern ones that are causing me trouble.  

What's strange is that the form is getting submitted, but some fields are missing.  I think the fields that are omitted are ones that I modified via javascript after the initial dom loaded, but I'm not completely sure.  

Here are a few of the user agents for which I've seen issues:
```
"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.3 Safari/536.11"
"Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko",
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
"Mozilla/5.0 (iPod touch; CPU iPhone OS 8_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12D508 Safari/600.1.4"
"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"
"Mozilla/5.0 (Linux; Android 5.1.1; SM-G530W Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.3 Chrome/38.0.2125.102 Mobile Safari/537.36"
```

I've changed to a jquery based "ujs-remote" style function for now and I'll see over the next couple of days if these errors go away.

**Comment by jalkoby** [comment]
forms are submitted due to a browser raises a js error and doesn't stop the default flow - submitting form
