### ISSUE TITLE
Origin missing from links form

### ISSUE THREAD

**Issue by denispeplin** [jalkoby/phoenix_ujs#4]
When I use `ujs-remote` with `form_for`, `phoenix_ujs` sends `Origin` header among others. But when using with `link`, it doesn't.
This leads to `Plug.CSRFProtection.InvalidCrossOriginRequestError` error on backend.

**Comment by jalkoby** [comment]
`Origin` header is not set by `phoenix_ujs`. I don't know why it doesn't set this header. Maybe this link will help you https://stackoverflow.com/questions/8456538/origin-null-is-not-allowed-by-access-control-allow-origin?answertab=votes#tab-top

**Comment by denispeplin** [comment]
Unfortunately, I have to time for deep investigation.
I found out that `link` works well with `"ujs-method": "delete"`. Only standard `get` links do not work.
So I've changed my `GET` link to `PUT` and solved the problem.
Thank you for quick response!
