### ISSUE TITLE
Meta tag not present on page load

### ISSUE THREAD

**Issue by brianlow** [jalkoby/phoenix_ujs#5]
To enable full page caching, we no longer render a CSRF token in the meta tag that UJS depends on.

We've made two workarounds:
* render a blank meta tag (so UJS doesn't log a warning)
* inject the token on ajax:beforeSend

Some ideas
* ability to tell UJS when to read the meta tag (we do set it eventually)
* ability to tell UJS the token to use (rather than read from the meta tag)

Great library, thanks!

**Comment by jalkoby** [comment]
yep - you can directly set csrf token like
```js
UJS.csrf.token = "your token";
```
there will be a warning from UJS, but it will work

**Comment by jalkoby** [comment]
as I see it helped
