### ISSUE TITLE
Submit form by Ajax from JS code

### ISSUE THREAD

**Issue by jarosluv** [jalkoby/phoenix_ujs#7]
Hello!

I have this form:
```html
<form accept-charset="UTF-8" action="/api/foo/9" id="form" method="post"  ujs-remote="ujs-remote">
    <input name="_method" type="hidden" value="put">
    <input name="_csrf_token" type="hidden" value="---">
    <input name="_utf8" type="hidden" value="✓">
</form>
```

And when I execute this js-code, it triggered native submit event (not ajax):
```js
form = document.getElementById("form");
form.submit();
```

@jalkoby what I do wrong?

**Comment by jarosluv** [comment]
I was able to solve this problem:

```js
  form = document.getElementById("form");
  customSubmitEvent = new Event("submit");
  Object.defineProperty(customSubmitEvent, "target", { value: form });
  document.dispatchEvent(customSubmitEvent)
```

But solution is too tricky. How we can refine it?

**Comment by jalkoby** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit Please read the documentation of the method

**Comment by jarosluv** [comment]
@jalkoby 

This doesn't help me. Please, give a more detailed answer.

**Comment by jalkoby** [comment]
the article say that 'form.submit' submits the form directly and there is **no guarantee** that "submit" event will be risen. So to handle submit by phoenix_ujs you need to trigger a submit event as I you did in the 2nd comment

**Comment by jarosluv** [comment]
@jalkoby 

If this is most right solution and we can't change code of library to capture all `submit` events. May be add this point to documentation at least?

**Comment by jalkoby** [comment]
Pull requests are welcome

**Comment by jarosluv** [comment]
@jalkoby 

I can do this, but I need your advice what path I must to choose:
1. Add this trick to Readme
1. Change code with `submit` event listener

If we choose second path, how we can change this code?

**Comment by jalkoby** [comment]
2nd point is not possible as it up to the browser to trigger or not "submit" event. What can be done is adding submitForm method in UJS and use it for such manual form submit. The implementation is already exist in the code(used in submit handler), but should it be an open api is a question? What was the reason for you to trigger submit method on form node?

**Comment by jarosluv** [comment]
@jalkoby 

It is several cases for this. For example, I want to submit form by hotkey, or when select box was changed, or when I want to "autosubmit" form when user have entered code from sms, or something else.

May be better to add `submit` listener to form with `ujs-remote` instead of `document`?

**Comment by jalkoby** [comment]
to be short: make "submit form" an open API  is a good idea, just send a PR
